#Google Analytics
analytics-id: #leave blank to not use Analytics

#Subtitle
subtitle:
  active: true
  text: There is nothing, just a hummingbird and the moon.

#Nav 
nav:
  pages:
    active: true
  social:
    active: false

#Featured images in homepage
featured-img:
  active: false


#Show date and read time under the post title
date-under-post:
  active: false

#Use MathJAX
mathjax:
  active: true

#Show related posts based on categories
related-posts:
  active: false
  title: "You May Also Enjoy"

#Comments
comments: false
